module Main in examples;

@Start
defun main (args : String[]) : void
{
    # This example shows how to throw and catch an exception. 

    try
    {
        F::println ("before");

        throw new Exception();

        F::println ("after");
    }
    catch (ex : Exception)
    {
        F::println ("handle");
    }
}