module Main in examples;

exception Disaster extends RuntimeException;

exception BankRun extends Disaster;

exception CivilUnrest extends Disaster;

exception Invasion extends Disaster;

exception Tornado extends Disaster;


@Start
defun main (args : String[]) : void
{
    Main::goverment(1);
    Main::goverment(2);
    Main::goverment(3);
    Main::goverment(4);
    Main::goverment(5);
}

defun goverment (n : int) : void
{
    try
    {
        F::println("Day " .. n);

        My::fema(n);

        F::println("Pander for votes.");
    }
    catch (problem1 : BankRun)
    {
        F::println("Issue Banker Bailout.");
    }
    catch (problem2 : Disaster)
    {
        F::println("Handle Disaster - " .. problem2.getClass());
    }

    F::println();
}

defun fema (n : int) : void
{
    try 
    {
        My::world(n);
    }
    catch (tornado : Tornado)
    {
        F::println ("Handle Tornado.");
    }
}

defun world (x : int) : void
{
    when (x == 1) then throw new BankRun();

    when (x == 2) then throw new CivilUnrest();

    when (x == 3) then throw new Invasion();

    when (x == 4) then throw new Tornado();
}

